<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.openelisglobal</groupId>
  <artifactId>openelisglobal-plugins</artifactId>
  <version>1.0</version>
  <packaging>pom</packaging>

  <modules>
    <module>./analyzers/CobasC111</module>
    <module>./analyzers/CobasIntegra400</module>
    <module>./analyzers/CobasTaqMan48DBS</module>
    <module>./analyzers/FacsCalibur</module>
    <module>./analyzers/FacsCantoII</module>
    <module>./analyzers/FacsPresto</module>
    <module>./analyzers/Fully</module>
    <module>./analyzers/Sysmex2000i</module>
    <module>./analyzers/SysmeXT</module>
    <module>./analyzers/SysmexXT4000i</module>
    <module>./analyzers/weberAnalyzer</module>
    <module>./analyzers/QuantStudio3</module>
    <module>./analyzers/GeneXpert</module>
    <module>./analyzers/Mindray</module>
    <module>./analyzers/GeneXpertFile</module>
    <module>./analyzers/SysmexXN-L</module>
    <module>./analyzers/SysmexXP</module>
    <module>./analyzers/pocH-100i</module>
  </modules>

  <properties>
    <springframework.version>6.2.2</springframework.version>
    <maven.compiler.target>21</maven.compiler.target>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.release>21</maven.compiler.release>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.openelisglobal</groupId>
      <artifactId>openelisglobal</artifactId>
      <version>3.2.1.0</version>
    </dependency>
    <dependency>
      <groupId>commons-validator</groupId>
      <artifactId>commons-validator</artifactId>
      <version>1.6</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-core</artifactId>
      <version>${springframework.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context-support</artifactId>
      <version>${springframework.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-csv</artifactId>
      <version>1.10.0</version>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-install-plugin</artifactId>
        <version>2.5.2</version>
        <inherited>false</inherited>
        <executions>
          <execution>
            <id>install-external-jar</id>
            <goals>
              <goal>install-file</goal>
            </goals>
            <phase>validate</phase>
            <configuration>
              <file>${project.basedir}/lib/openelisglobal-3.2.1.0.jar</file>
              <groupId>org.openelisglobal</groupId>
              <artifactId>openelisglobal</artifactId>
              <version>3.2.1.0</version>
              <packaging>jar</packaging>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!-- Code formatter -->
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>2.43.0</version>
        <configuration>
          <pom>
            <sortPom>
              <expandEmptyElements>false</expandEmptyElements>
            </sortPom>
            <trimTrailingWhitespace/>
            <endWithNewline/>
            <indent>
              <spaces>true</spaces>
            </indent>
          </pom>
          <!-- define a language-specific format -->
          <java>
            <googleJavaFormat/>
            <!-- Use default Google Java Formatter -->
            <removeUnusedImports/>
            <importOrder/>
          </java>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
